// Code generated by Icestudio 0.8.0

`default_nettype none

//---- Top entity
module main (
 input [32:1] v887015,
 input [32:1] v41151f,
 output [32:1] v0f71b5,
 output [0:7] vinit
);
 wire [0:31] w0;
 wire [0:31] w1;
 wire [0:31] w2;
 assign w0 = v41151f;
 assign w1 = v887015;
 assign v0f71b5 = w2;
 main_v201d12 v201d12 (
  .b(w0),
  .a(w1),
  .out(w2)
 );
 assign vinit = 8'b00000000;
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/

module main_v201d12 (
 input [32:1] a,
 input [32:1] b,
 output [32:1] out
);
 assign out = a >> b
endmodule
